// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkAEzNY5zLEHiXTMpPq0tZ6MJkADkPB2I',
    appId: '1:535250592910:web:5ed68aed7b4696d52515df',
    messagingSenderId: '535250592910',
    projectId: 'petwell-g44',
    authDomain: 'petwell-g44.firebaseapp.com',
    storageBucket: 'petwell-g44.firebasestorage.app',
    measurementId: 'G-QEQD8VHH7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt2cnqLMnjrxEAV33j3mPwE1eLqTopydU',
    appId: '1:535250592910:android:aa813e71593142772515df',
    messagingSenderId: '535250592910',
    projectId: 'petwell-g44',
    storageBucket: 'petwell-g44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6YXiqdjtjv405O-UvvDJjzR1TlQSJgqc',
    appId: '1:535250592910:ios:61259be7eee593302515df',
    messagingSenderId: '535250592910',
    projectId: 'petwell-g44',
    storageBucket: 'petwell-g44.firebasestorage.app',
    iosBundleId: 'com.example.petwell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6YXiqdjtjv405O-UvvDJjzR1TlQSJgqc',
    appId: '1:535250592910:ios:61259be7eee593302515df',
    messagingSenderId: '535250592910',
    projectId: 'petwell-g44',
    storageBucket: 'petwell-g44.firebasestorage.app',
    iosBundleId: 'com.example.petwell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkAEzNY5zLEHiXTMpPq0tZ6MJkADkPB2I',
    appId: '1:535250592910:web:61c8b5e1e3eb605a2515df',
    messagingSenderId: '535250592910',
    projectId: 'petwell-g44',
    authDomain: 'petwell-g44.firebaseapp.com',
    storageBucket: 'petwell-g44.firebasestorage.app',
    measurementId: 'G-54XZVTZ1FW',
  );
}
